namespace Relay.Api.Data;

/// <summary>
/// Maps to the `accounts` table defined in schema.sql. IDs are supplied by the
/// seed data, not generated by the database.
/// </summary>
public class Account
{
    public int Id { get; set; }
    public string Name { get; set; } = default!;
    public string Industry { get; set; } = default!;

    /// <summary>IANA timezone id, e.g. "America/Chicago".</summary>
    public string Timezone { get; set; } = default!;

    /// <summary>UTC. See <see cref="RelayDbContext"/> for how Kind is preserved.</summary>
    public DateTime CreatedAt { get; set; }

    public ICollection<ActivityEvent> ActivityEvents { get; set; } = new List<ActivityEvent>();
}
