namespace Relay.Api.Data;

/// <summary>
/// Maps to the `activity_events` table defined in schema.sql. IDs are supplied by
/// the seed data, not generated by the database. Duplicate rows (same account/
/// location/event_type/occurred_at, different id) are intentionally preserved —
/// see PLAN.md.
/// </summary>
public class ActivityEvent
{
    public int Id { get; set; }
    public int AccountId { get; set; }

    /// <summary>The account's site/branch where the activity occurred.</summary>
    public string Location { get; set; } = default!;

    /// <summary>'call_received' | 'lead_created' | 'appointment_set'.</summary>
    public string EventType { get; set; } = default!;

    /// <summary>UTC. See <see cref="RelayDbContext"/> for how Kind is preserved.</summary>
    public DateTime OccurredAt { get; set; }

    /// <summary>Only meaningful for calls; may be NULL.</summary>
    public int? DurationSeconds { get; set; }

    /// <summary>e.g. 'connected' | 'missed' | 'voicemail' | 'converted' | 'no_show'; may be NULL.</summary>
    public string? Outcome { get; set; }

    public Account Account { get; set; } = default!;
}
